### ISSUE TITLE
Checkmate didn't end game

### ISSUE THREAD

**Issue by lynchde** [cjsaylor/chessbot#71]
**Describe the bug**
I've just played a game that led to a checkmate (see screenshot), however the game didn't end. No moves were valid. We ended by resignation

**To Reproduce**
1. Follow this crazy game! 1.e4 d5 2.e5 c6 3.g3 g5 4.Qh5 Bg7 5.Bh3 g4 6.Bxg4 Bxg4 7.Qxg4 Bh6 8.Qh5 Qc7 9.e6 Kd8 10.exf7 Nf6 11.Qxh6 Nbd7 12.Ne2 c5 13.Nf4 Qd6 14.O-O Ne5 15.f8=Q+ Rxf8 16.Qxf8+ Kd7 17.Qxa8 Kc7 18.Nc3 Nf3+ 19.Kh1 d4 20.Nb5+ Kc6 21.Nxd6 Kxd6 22.Kg2 Ng5 23.Qd8+ Kc6 24.Qxe7 h5 25.Qxf6+ Kb5 26.a4+ Kc4 27.Qd8 Kb4 28.d3 c4 29.Qd6+ Ka5 30.b4+ 1-0

**Expected behavior**
We expected the game to end. If there was some move that we should have made instead, please feel free to cancel this issue.

**Screenshots**
<img width="318" alt="image" src="https://user-images.githubusercontent.com/15089758/117551153-4648ad00-b012-11eb-90e9-8ecb50742387.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser slack app
 - Version 4.16.0

**Additional context**

**Comment by cjsaylor** [comment]
Hi @lynchde! Thanks for submitting an issue.

It is a tricky game, but it actually turns out not to be checkmate. The black pawn on `c4` can perform an "en passant" move, meaning the move `c4b3` is valid and would capture the white pawn at `b4`.

That being said, it is unlikely that black can recover from such an onslaught!
